### ISSUE TITLE
No Version number in MacOS "Get Info" dialog

### ISSUE THREAD

**Issue by JDW1** [dougg3/mac-rom-simm-programmer.software#9]
I began using the MacOS edition of this great software when it was version 1.1.0, which I downloaded from [this BMOW webpage](https://www.bigmessowires.com/mac-rom-inator-ii-programming/) for use with the [BMOW SIMM programmer](https://www.bigmessowires.com/2016/06/07/simm-programmer-for-rom-inator-ii/).  I downloaded version 1.1.2 just now and found it has the same issue as v1.1.0. 

Specifically, when you select the app and press CMD-I, **_the "Get Info" dialog appears but doesn't display a version number_**.  

Certainly, I can launch the app and then click the SIMMProgrammer menu and then choose About SIMMProgrammer to learn what version it is, but to be 100% consistent with the MacOS UI, it would be appreciated if the app's version number could be made to appear in the "Get Info" box. Mac users expect that to be display in "Get Info" so it would be nice if the app could recognize that.

Lastly, the description says _"Incorporated all of Steve Chamberlin's changes to the programmer utility"_ which **_implies_** v1.1.2 should still work fine with the BMOW SIMM Programmer; but if that is true, perhaps saying so more clearly would be more reassuring to those who own the BMOW edition programmer.

**Comment by dougg3** [comment]
Hi @JDW1 ,

Thank you for pointing out the issue with the version number not appearing in the Get Info window. I fixed this and uploaded a new Mac release of version 1.1.2 that correctly shows the version info. If you re-download it, you should see the version info now. I also discovered that Windows had a similar issue with the properties dialog not displaying the version info, but I won't release a new build of the Windows version until I make other changes. I had to submit the exe to Microsoft for them to review and check for viruses in order to avoid the Windows SmartScreen warning when you try to run it, and don't want to go through that manual review process again until I have more substantial changes.

I updated the README and release note to make it more clear that this software is compatible with the BMOW and CayMac Vintage programmers as well. They are all effectively the same product in slightly different form factors and they all run the same software and firmware, just like my original.

I appreciate your feedback!
